---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-pod-network-latency-sa
  namespace: bookinfo
  labels:
    name: bookinfo-pod-network-latency-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: bookinfo-pod-network-latency-sa
  namespace: bookinfo
  labels:
    name: bookinfo-pod-network-latency-sa
rules:
- apiGroups: ["","litmuschaos.io","batch"]
  resources: ["pods","jobs","pods/log","events","chaosengines","chaosexperiments","chaosresults"]
  verbs: ["create","list","get","patch","update","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: bookinfo-pod-network-latency-sa
  namespace: bookinfo
  labels:
    name: bookinfo-pod-network-latency-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bookinfo-pod-network-latency-sa
subjects:
- kind: ServiceAccount
  name: bookinfo-pod-network-latency-sa
  namespace: bookinfo